# Generated by Django 4.2.6 on 2023-12-08 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekseer_api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Full name should contain only letters.', max_length=255, validators=[django.core.validators.RegexValidator(message='Full name must contain only Arabic or English letters.', regex='[a-zA-Z\u0600-ۿ]+')]),
        ),
    ]
